Repository ParkJong-Hun/Animal_Island, pull requests merged in 2021-06, with the labels that each got.

#33 2021/06/02 회원가입, 채팅화면 업데이트
  .idea/runConfigurations.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/petstone/project/animalisland/RegisterActivity.java
  app/src/main/java/petstone/project/animalisland/activity/ChatActivity.java
  app/src/main/java/petstone/project/animalisland/activity/LoginActivity.java
  app/src/main/java/petstone/project/animalisland/activity/MainActivity.java
  app/src/main/java/petstone/project/animalisland/activity/RegisterActivity.java
  app/src/main/res/layout/user_create.xml
Labels: 도움 필요, 업데이트

#38 2021/06/03 업데이트
  app/src/main/java/petstone/project/animalisland/activity/ChatActivity.java
  app/src/main/java/petstone/project/animalisland/activity/ChatComponent.java
  app/src/main/res/layout/chatlist_component.xml
Labels: 업데이트

#39 Jonghun
  .idea/compiler.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/petstone/project/animalisland/activity/LoginActivity.java
  app/src/main/java/petstone/project/animalisland/activity/MainActivity.java
  app/src/main/java/petstone/project/animalisland/activity/MypageInfoEditActivity.java
  app/src/main/java/petstone/project/animalisland/activity/RegisterActivity.java
  app/src/main/java/petstone/project/animalisland/activity/SelectFreeRehomeActivity.java
  app/src/main/java/petstone/project/animalisland/activity/SelectSellRehomeActivity.java
  app/src/main/java/petstone/project/animalisland/component/ChatComponent.java
  app/src/main/java/petstone/project/animalisland/component/FreeRehomeComponent.java
  app/src/main/java/petstone/project/animalisland/component/MypageComponent.java
  app/src/main/java/petstone/project/animalisland/component/PetFriendComponent.java
  app/src/main/java/petstone/project/animalisland/component/RehomeComponent.java
  app/src/main/java/petstone/project/animalisland/component/SellRehomeComponent.java
  app/src/main/java/petstone/project/animalisland/other/ChatAdapter.java
  app/src/main/java/petstone/project/animalisland/other/FreeRecycleAdapter.java
  app/src/main/java/petstone/project/animalisland/other/FreeRehomeList.java
  app/src/main/java/petstone/project/animalisland/other/MypageCustomListAdapter.java
  app/src/main/java/petstone/project/animalisland/other/MypageEventDialog.java
  app/src/main/java/petstone/project/animalisland/other/MypageNewsDialog.java
  app/src/main/java/petstone/project/animalisland/other/PetfriendCustomAdapter.java
  app/src/main/java/petstone/project/animalisland/other/SellRecycleAdapter.java
  app/src/main/java/petstone/project/animalisland/other/SellRehomeList.java
  app/src/main/java/petstone/project/animalisland/other/VPAdapter.java
  app/src/main/java/petstone/project/animalisland/other/petfriend_recycelview_adapter/PetfriendRecycleAdapter.java
  app/src/main/java/petstone/project/animalisland/other/petfriend_recycelview_adapter/PetfriendSearchData.java
  app/src/main/java/petstone/project/animalisland/other/petfriend_recycelview_adapter/RecyclerDecoration.java
Labels: 업데이트

#40 2021/06/03 10:22 머지 충돌 고침
  app/src/main/java/petstone/project/animalisland/other/FreeRecycleAdapter.java
Labels: 업데이트

#44 Jonghun
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/petstone/project/animalisland/activity/MypageInfoEditActivity.java
  app/src/main/java/petstone/project/animalisland/activity/PetfriendUserApplyActivity.java
  app/src/main/java/petstone/project/animalisland/activity/PetfriendUserSelect.java
  app/src/main/java/petstone/project/animalisland/activity/RehomeFreeSubmitActivity.java
  app/src/main/java/petstone/project/animalisland/activity/SelectFreeRehomeActivity.java
  app/src/main/java/petstone/project/animalisland/activity/UserCreateAcitivity.java
  app/src/main/java/petstone/project/animalisland/other/MypageCustomListAdapter.java
  app/src/main/java/petstone/project/animalisland/other/PetfriendCustomAdapter.java
  app/src/main/res/layout/main.xml
  app/src/main/res/layout/petfriend_component.xml
  app/src/main/res/layout/petfriend_user_apply.xml
  app/src/main/res/layout/toolbar_mypage_edit_info.xml
  app/src/main/res/layout/toolbar_mypage_sell_apply.xml
Labels: 최종 업데이트

#45 2021/06/07 19:41 채팅 목록 업데이트
  app/src/main/AndroidManifest.xml
  app/src/main/java/petstone/project/animalisland/activity/ChatActivity.java
  app/src/main/java/petstone/project/animalisland/activity/MainActivity.java
  app/src/main/java/petstone/project/animalisland/component/ChatListComponent.java
  app/src/main/java/petstone/project/animalisland/other/ChatImsiAdapter.java
  app/src/main/res/layout/chat.xml
  app/src/main/res/layout/chat_list.xml
  app/src/main/res/layout/chatlist_component.xml
Labels: 업데이트, 임시
